package com.runner.assinador.domain.exception;

public enum DomainErrorCode {

    TIMESTAMP_OUT_OF_TOLERANCE_WINDOW("TIMESTAMP.OUT-OF-TOLERANCE-WINDOW"),
    FORMAT_DUPLICATE_FULLURL("FORMAT.DUPLICATE-FULLURL"),
    FORMAT_PROVENANCE_TARGET_DUPLICATE("FORMAT.PROVENANCE-TARGET-DUPLICATE"),
    FORMAT_TARGET_REFERENCE_MISSING("FORMAT.TARGET-REFERENCE-MISSING"),
    FORMAT_BUNDLE_RESOURCE_MISSING("FORMAT.BUNDLE-RESOURCE-MISSING"),
    FORMAT_JSON_MALFORMED("FORMAT.JSON-MALFORMED"),
    FORMAT_BASE64_INVALID("FORMAT.BASE64-INVALID"),
    FORMAT_JWS_MALFORMED("FORMAT.JWS-MALFORMED");

    private final String code;

    DomainErrorCode(String code) { this.code = code; }

    public String getCode() { return code; }
}